# Generated by Django 5.2.6 on 2025-10-07 12:03

import apps.course.fields
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_remove_courses_course_id_base_alter_attachdata_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachdata',
            name='id',
            field=apps.course.fields.SymbolIdField(max_length=16, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(16), django.core.validators.MinLengthValidator(16)], verbose_name='symbol id'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='id',
            field=apps.course.fields.SymbolIdField(max_length=16, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(16), django.core.validators.MinLengthValidator(16)], verbose_name='symbol id'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='id',
            field=apps.course.fields.SymbolIdField(max_length=16, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(16), django.core.validators.MinLengthValidator(16)], verbose_name='symbol id'),
        ),
    ]
