"""
Django settings for classroom project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-0m_kcd4bgi==4n7eb8*t%fv9gr6*=f*_*-1*qm&=zpbc+1*e#g'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

# Внешние приложения
INSTALLED_APPS += [
    'rest_framework',
    'debug_toolbar',
    'django_filters'
]

# Наши приложения
INSTALLED_APPS += [
    'apps.authorization.apps.AuthorizationConfig',
    'apps.notifications.apps.NotificationsConfig',
    'apps.course.apps.CourseConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "debug_toolbar.middleware.DebugToolbarMiddleware",
    'classroom.middleware.DisableCSRFForAPI', # TEST
]

ROOT_URLCONF = 'classroom.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'classroom.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
import os

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('POSTGRES_NAME', 'postgres'),
        'USER': os.environ.get('POSTGRES_USER', 'postgres'),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD', 'postgres'),
        'HOST': 'db',
        'PORT': 5432,
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# / Переопределенные настройки /
AUTH_USER_MODEL = "authorization.CustomUser"

STATIC_ROOT = BASE_DIR / STATIC_URL
MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / MEDIA_URL


INTERNAL_IPS = [
    "127.0.0.1",
]


REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',  # Для сессий
        'rest_framework.authentication.BasicAuthentication',    # Для тестирования
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'apps.authorization.permissions.IsVerified',  # Требует верификации (подтверждения аккаунта)
        'rest_framework.permissions.IsAuthenticated',  # Требует аутентификации
    ],
    #Ограничение запросов
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'user': '1000/day'
    }
}
#EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend' # для тестов

# для готового приложения
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_HOST = 'smtp.yandex.ru' # адрес почтового сервера
EMAIL_PORT = 587
EMAIL_USE_SSL = False
EMAIL_USE_TLS = True
EMAIL_HOST_USER = '<ваша почта>' # почта для отправки
EMAIL_HOST_PASSWORD = '<пароль>'  # пароль почты

DEFAULT_FROM_EMAIL = EMAIL_HOST_USER # почта, которую увидят получатели 
SERVER_EMAIL = EMAIL_HOST_USER
EMAIL_ADMIN = EMAIL_HOST_USER

#Настройка кэша для Redis
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": "redis://redis:6379/1",
    }
}

import redis
#Проерка подключения Redis
try:
    MY_REDIS = redis.Redis(
        host = 'redis',
        port = 6379,
        db = 1,
    )
    MY_REDIS.ping()
    print('REDIS CONNECTION SUCCESSFUL!')

except redis.exceptions.RedisError as e:
    print(f"REDIS CONNECTION FAILED: {e}")


DEBUG_TOOLBAR_CONFIG = {
    "SHOW_TOOLBAR_CALLBACK": lambda request: DEBUG,
}

#Настройка логирования
from loguru import logger
import sys
import queue
from threading import Thread

logs_queue = queue.Queue()

def loguru_config():
    while True:
        try:
            log = logs_queue.get(timeout=1)
            if log is None:
                break
            with open('loguru.log', 'a') as file:
                file.write(log + "\n")
        except queue.Empty:
            continue

def to_queue(message):
    logs_queue.put(f"{message.record['time']:%Y-%m-%d %H:%M:%S} | {message.record['level'].name} | {message.record['message']}")

logger.remove(0)
logger.add(sys.stderr, level="INFO")
logger.add(to_queue, level="INFO")

log_thread = Thread(target=loguru_config, daemon=True)
log_thread.start()



#http://localhost:8000
